Polynomial_regression:
  degree: 5

Random_Forest:
  rf_n_estimators: 200
  rf_max_depth: null
  rf_min_samples_split:  2
  rf_min_samples_leaf: 1

XGBoost:
  xgb_n_estimators: 300
  xgb_learning_rate: 0.05
  xgb_max_depth: 6
  xgb_subsample: 0.8
  xgb_colsample_bytree: 0.8
  xgb_reg_lambda: 1.0

MLP:
  mlp_hidden_layers:
    - 128
    - 64
  mlp_activation: "relu"
  mlp_solver: "adam"
  mlp_learning_rate: 0.001
  mlp_max_iter: 500
